import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import Footer from "@/components/layout/Footer";
import Header from "@/components/layout/Header";
import { ThemeProvider } from "@/components/layout/ThemeToggle";
import Axe from "@/components/common/Axe";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider>
      <ClerkProvider>
        <html lang="en">
          <Axe />
          <body className={`${inter.className} flex flex-col h-full`}>
            <Header />
            <div className="flex-grow bg-gradient-to-b dark:from-slate-300 dark:to-slate-800 from-slate-100 to-slate-500">
              {children}
            </div>
            <Footer />
          </body>
        </html>
      </ClerkProvider>
    </ThemeProvider>
  );
}
