import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import Footer from "@/components/layout/Footer";
import Header from "@/components/layout/Header";
import { ThemeProvider } from "@/components/layout/ThemeToggle";
import Axe from "@/components/common/Axe";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider>
      <ClerkProvider>
        <html lang="en">
          <Axe />
          <body
            className={`${inter.className} bg-slate-200 text-slate-900 flex-col divide-y divide-slate-400 h-full h-dvh max-h-dvh`}
          >
            <Header />
            <div className="flex-grow">{children}</div>
            <Footer />
          </body>
        </html>
      </ClerkProvider>
    </ThemeProvider>
  );
}
